// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4980.TestRobot.subsystems;

import org.usfirst.frc4980.TestRobot.RobotMap;
import org.usfirst.frc4980.TestRobot.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ShooterWheels extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon cANTalonLeft = RobotMap.shooterWheelsCANTalonLeft;
    private final CANTalon cANTalonRight = RobotMap.shooterWheelsCANTalonRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new BallCapture());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public ShooterWheels(){
    	cANTalonRight.setInverted(true);
    	
    }
    public void Stop(){
    	cANTalonLeft.set(0.0);
    	cANTalonRight.set(0.0);
    }
    public void Capture(double speed){
    	cANTalonLeft.set(speed);
    	cANTalonRight.set(speed);
    	
    }
    public void ShootHigh(){
    	cANTalonLeft.set(-1.0);
    	cANTalonRight.set(-1.0);
    }
    public void ShootLow(){
    	cANTalonLeft.set(-0.3);
    	cANTalonRight.set(-0.3);
    }
}

