// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4980.TestRobot.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4980.TestRobot.Robot;

/**
 *
 */
public class  AutonomousDriveForward extends Command {
	private double m_timeout;
	 public AutonomousDriveForward() {
		 m_timeout = -1;
	 }
	    	
	    	
    public AutonomousDriveForward(double timeout) {
    	m_timeout = timeout;
    	
    	
    	
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveSystem);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	if(m_timeout>0)
    		setTimeout(m_timeout);
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
     Robot.driveSystem.driveForward(0.5);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	if(m_timeout < 0)
    		return false;
        return isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveSystem.stop();
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.driveSystem.stop();
    }
}
